```{r}

library(magrittr)
library(tidyverse)
library(graphics)
library(PMCMR)

```


Plotting 


```{r}

## m3 = estimate_profiles(d,
##                        colnames_lpa,
##                        n_profiles = , 
##                        model = 2,
##                        return_orig_df = T)


q8_plot = plot_profiles(m3[, c("Q8_v2_1", "Q8_v2_2", "Q8_v2_3", "Q8_v2_4", "profile", "posterior_prob")])

ggsave(device="png", plot=q8_plot, filename="./plots/q8_plot.png", scale=.2, height = 1024, width = 1024, units = "mm")


```

# Testing

## DONE: number of pieces of software used
### in general
### per question

```{r}

vars1 = software_cleaned  %>%
  group_by(RecordNo) %>%
  mutate(n_unique_soft = n()) %>%
  ungroup() %>%
  group_by(RecordNo, q) %>%
  mutate(n_unique_soft_per_q = n()) %>%
  ungroup() %>% dplyr::select(-a, -q)

```

## Number of software used out of top-10


```{r}

software_cleaned %>% View

vars2 = software_cleaned  %>%
  filter(!(.$a2 %in% (software_aggregated %>% top_n(10, n) %$% a2))) %>% 
  group_by(RecordNo) %>%
  mutate(n_unique_soft_non_pop= n()) %>%
  ungroup() %>%
  group_by(RecordNo, q) %>%
  mutate(n_unique_soft_per_q_non_pop= n()) %>%
  ungroup() %>% dplyr::select(-a, -q)


```
# Stat - Occupation/Profile

```{r}

m3 %>%
  group_by(profile, Occupation) %>%
  tally() %>%
  dplyr::mutate(perc_per_profile = n / sum(n) * 100) %>%
  ungroup() %>%
  dplyr::mutate(perc_total = n / sum(n) * 100) %>% View



```


# Mosaicplot: Occupation/Profile

```{r}

corr_m3 = m3 %>%
  group_by(profile, Occupation) %>%
  tally() %>%
  tidyr::spread(Occupation, n)


png("./plots/mosaic_occupation_profile.png",
    widt = 1024, height = 1024, units = "px", pointsize = 26)
mosaicplot(corr_m3[,-1], shade = TRUE, las=2, main = "Occupations per Profile")
dev.off()


with(dev.new(),
     mosaicplot(corr_m3[,-1], shade = TRUE, las=2, main = "Occupations per Profile"))



```



```{r}

## TODO: ask about NAs.
## UPD: one assumption might be that is respondent did not indicated software, then populate this with random from top 5-10
# vars2$RecordNo %>% unique() %>% length()
# inner_join(m3, vars2, by = "RecordNo") %$% unique(RecordNo)  %>% length()

tmp = inner_join(m3, vars2, by = "RecordNo")
tmp1 = inner_join(m3, vars1, by = "RecordNo")

pairwise.wilcox.test(tmp$n_unique_soft_non_pop, 
                     tmp$profile, 
                     p.adjust.method="bonferroni",
                     paired = FALSE)

pairwise.wilcox.test(tmp$n_unique_soft_per_q_non_pop, 
                     tmp$profile, 
                     p.adjust.method="bonferroni",
                     paired = FALSE)

ttt = pairwise.wilcox.test(tmp$n_unique_soft_per_q_non_pop, 
                     tmp$profile, 
                     p.adjust.method="bonferroni",
                     paired = FALSE)

texreg(ttt)

screenreg(ttt)

## TODO: might be kinda cool in conjunction with smth else, elaborate on this
# Those capable of reprogramming and those who are not tend to use the same amount of soft. Check for occupations later
# Kinda a step towards the point that even possibility to reprogram does not provide s

median(tmp$n_unique_soft_non_pop[tmp$profile == 1])
median(tmp$n_unique_soft_non_pop[tmp$profile == 2])
median(tmp$n_unique_soft_non_pop[tmp$profile == 3])
median(tmp$n_unique_soft_non_pop[tmp$profile == 4])
median(tmp$n_unique_soft_non_pop[tmp$profile == 5])

# not a rocket science, it is signigifant everywhere
kruskal.test(data = m3, Q8_v2_1 ~ profile)
kruskal.test(data = m3, Q8_v2_2 ~ profile)
kruskal.test(data = m3, Q8_v2_3 ~ profile)
kruskal.test(data = m3, Q8_v2_4 ~ profile)

inner_join(m3[m3$profile == 2,] %>% dplyr::arrange(sort(.$posterior_prob, decreasing = TRUE)) %>% top_n(n=10, posterior_prob),
           software_cleaned,
           by = "RecordNo") %>% View()


inner_join(m3[m3$profile == 3,] %>% dplyr::arrange(sort(.$posterior_prob, decreasing = TRUE)) %>% top_n(n=10, posterior_prob),
           software_cleaned,
           by = "RecordNo") %>% View()


# posthoc.
# post hoc testing

pairwise.wilcox.test(m3$Q8_v2_1, 
                     m3$profile, 
                     p.adjust.method="bonferroni",
                     paired = FALSE)

pairwise.wilcox.test(m3$Q8_v2_2, 
                     m3$profile, 
                     p.adjust.method="bonferroni",
                     paired = FALSE)


pairwise.wilcox.test(m3$Q8_v2_3, 
                     m3$profile, 
                     p.adjust.method="bonferroni",
                     paired = FALSE)


pairwise.wilcox.test(m3$Q8_v2_4, 
                     m3$profile, 
                     p.adjust.method="bonferroni",
                     paired = FALSE)



```


```{r}



```
